"""initial_listings_table

Revision ID: fcbc080d5e4f
Revises: 
Create Date: 2025-11-26 12:10:27.793171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcbc080d5e4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_url', sa.String(length=500), nullable=False),
    sa.Column('property_id', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=10), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('baths', sa.Float(), nullable=True),
    sa.Column('sqft', sa.Integer(), nullable=True),
    sa.Column('list_date', sa.String(length=50), nullable=True),
    sa.Column('has_septic_system', sa.Boolean(), nullable=False),
    sa.Column('has_private_well', sa.Boolean(), nullable=False),
    sa.Column('septic_mentions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('well_mentions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agent_url', sa.String(length=500), nullable=True),
    sa.Column('agent_name', sa.String(length=255), nullable=True),
    sa.Column('agent_phone', sa.String(length=50), nullable=True),
    sa.Column('brokerage_name', sa.String(length=255), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('times_seen', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_url')
    )
    op.create_index(op.f('ix_listings_city'), 'listings', ['city'], unique=False)
    op.create_index(op.f('ix_listings_county'), 'listings', ['county'], unique=False)
    op.create_index(op.f('ix_listings_has_private_well'), 'listings', ['has_private_well'], unique=False)
    op.create_index(op.f('ix_listings_has_septic_system'), 'listings', ['has_septic_system'], unique=False)
    op.create_index(op.f('ix_listings_property_id'), 'listings', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_property_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_has_septic_system'), table_name='listings')
    op.drop_index(op.f('ix_listings_has_private_well'), table_name='listings')
    op.drop_index(op.f('ix_listings_county'), table_name='listings')
    op.drop_index(op.f('ix_listings_city'), table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
